### ISSUE TITLE
Cannot login with token - InvalidAccessKeyIdError

### ISSUE THREAD

**Issue by hkai-tony-li** [aliyun/acr-login#10]
![2021-05-27 18_01_16-build-deployment-image yml - mai-cms  WSL_ Ubuntu  - Visual Studio Code](https://user-images.githubusercontent.com/80728483/119807830-1d7f4d80-bf16-11eb-9ce8-febc990d383c.png)
![2021-05-27 18_00_42-trial 3 acr login · hkai-io_mai-cms@21a5ae5 and 16 more pages - Work - Microsoft](https://user-images.githubusercontent.com/80728483/119807841-1eb07a80-bf16-11eb-996a-086b19f2cc69.png)

My account has permission 'AliyunContainerRegistryFullAccess'
I can use my access key to configure and access CR using the Aliyun CLI
I had double check the access key and access secret and tried two different pair but still invalid.
Thanks!

**Comment by jackalcooper** [comment]
Same here. Have you revolved this? I can use a access key pair to login into OSS but fail with this action
